config/routes.rb
Rails.application.routes.draw do
  resources :tracks
  resources :exams
  resources :applications
  resources :openings
  resources :designations
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # General Pages
  root 'pages#index'
  get '/guide' => 'pages#guide'

  # Employee List
  resources :participants
  get '/participants/program' => 'participants#indexProg'
  
  # Designation List
  resources :designations

  # Openings List
  resources :openings
  patch '/openings/:id/cancel' => 'openings#cancel', as: :cancel_opening
  patch '/openings/:id/reopen' => 'openings#reopen', as: :reopen_opening

  # Applications List
  get '/open_roles' => 'opening#open'
end

app/models/opening.rb
class Opening < ApplicationRecord
    serialize :level
end

app/controllers/openings_controller.rb
class OpeningsController < ApplicationController
  before_action :set_opening, only: %i[ show edit update destroy cancel reopen ]
  before_action :choice_field, only: %i[ new edit ]
  before_action :check_action, only: %i[ create update ]

  # GET /openings or /openings.json
  def index
    @draft = sort_category("Draft")
    puts @draft
    @pending = sort_category("Pending Applications")
    @offered = sort_category("Position Offered")
    @accepted = sort_category("Accepted")
    @complete = sort_category("Complete")
    @cancelled = sort_category("Cancelled")
  end

  # Get open positions for applications
  def open
    @student = Opening.where(status: "Pending Applications", position: "Full Time", program: true)
    @intern = Opening.where(status: "Pending Applications", position: "Internship", program: true)
    @general = Opening.where(status: "Pending Applications", position: "Full Time", program: false)
  end

  # GET /openings/1 or /openings/1.json
  def show
  end

  # GET /openings/new
  def new
    @opening = Opening.new
  end

  # GET /openings/1/edit
  def edit
  end

  # POST /openings or /openings.json
  def create
    @opening = Opening.new(opening_params)
    @opening.status = pubstat ? "Pending Applications" : "Draft"

    respond_to do |format|
      if @opening.save
        format.html { redirect_to openings_path }
        format.json { render :show, status: :created, location: @opening }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @opening.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /openings/1 or /openings/1.json
  def update
    @opening.status = pubstat ? "Pending Applications" : "Draft"
    puts @opening

    respond_to do |format|
      if @opening.update(opening_params)
        format.html { redirect_to openings_path }
        format.json { render :show, status: :ok, location: @opening }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @opening.errors, status: :unprocessable_entity }
      end
    end
  end

  def cancel
    @opening.status = "Cancelled"
    puts @opening.firstname

    respond_to do |format|
      if @opening.update(params.permit(:status))
        format.html { redirect_to openings_path }
        format.json { render :show, status: :ok, location: @opening }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @opening.errors, status: :unprocessable_entity }
      end
    end
  end

  def reopen
    @opening.status = "Draft"
    puts @opening.firstname

    respond_to do |format|
      if @opening.update(params.permit(:status))
        format.html { redirect_to edit_opening_path(@opening) }
        format.json { render :show, status: :ok, location: @opening }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @opening.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /openings/1 or /openings/1.json
  def destroy
    @opening.destroy
    respond_to do |format|
      format.html { redirect_to openings_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_opening
      @opening = Opening.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def opening_params
      params.require(:opening).permit(:firstname, :lastname, :qualification, :status, :position, :geid, :program, :description, :responsibility, :level => [])
    end

    # Confirm status
    def pubstat
      params[:commit] == "Submit"
    end

    # Set choices
    def choice_field
      @jobtype = ["Internship", "Full Time"]
      @level = ["Any", "Pre-Associate", "Near Associate", "Recent Associate", "Near Fellow"]
    end

    # Set index filters
    def sort_category(statname)
      Opening.where(:status => statname).sort_by {|obj| obj.position}.sort_by {|obj| obj.firstname}.sort_by {|obj| obj.lastname}
    end

    # Check for cancellation
    def check_action
      if params[:cancel]
        redirect_to openings_path
      end
    end
end

app/helpers/openings_helper.rb
module OpeningsHelper
end

app/views/openings/_form.html.erb
<%= form_with(model: opening) do |form| %>
  <% if opening.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(opening.errors.count, "error") %> prohibited this opening from being saved:</h2>

      <ul>
        <% opening.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/openings/edit.html.erb
<h1>Edit Opening</h1>
<h2>Current status: <%= @opening.status %></h2>

<%= form_with model: @opening do |x| %>
    <div class="section">
        <table>
            <tbody>
                <tr>
                    <td>Manager First Name</td>
                    <td><%= x.text_field :firstname %></td>
                    <td>Manager Last Name</td>
                    <td><%= x.text_field :lastname %></td>
                </tr>
                <tr>
                    <td>Manager Employee ID</td>
                    <td><%= x.text_field :geid %></td>
                    <td rowspan=3>Level</td>
                    <td rowspan=3>
                        <%= x.select(:level, @level, { include_hidden: false },
                            { :multiple => true, :size => @level.length }
                        ) %>
                    </td>
                </tr>
                <tr>
                    <td>Program Position</td>
                    <td><%= x.check_box :program, :checked => true %> Check this box if this position will be a program position.</td>
                </tr>
                <tr>
                    <td>Position Type</td>
                    <td><%= x.select :position, @jobtype, {include_blank: "", selected: @opening.position} %></td>
                </tr>
                <tr>
                    <td>Job Description</td>
                    <td colspan=3><%= x.text_area :description, :rows => 5 %></td>
                </tr>
                <tr>
                    <td>Responsibilities</td>
                    <td colspan=3><%= x.text_area :responsibility, :rows => 5 %></td>
                </tr>
                <tr>
                    <td>Qualifications</td>
                    <td colspan=3><%= x.text_area :qualification, :rows => 5 %></td>
                </tr>
            </tbody>
        </table>
    </div>

    <%= button_tag "Cancel", :type => "submit", name: "cancel", class: "action" %>
    <%= x.submit "Submit", class: "action program", data: { confirm: "You will not be able to edit this entry upon submission. Are you sure you want to submit?"} %>
    <%= x.submit "Save as Draft", class: "action draft" %>
<% end %>

app/views/openings/index.html.erb
<%= javascript_pack_tag "openings" %>
<h1>All Job Openings</h1>

<%= button_to 'New Job Opening', new_opening_path, :method => "get", class: "action", id: "new" %>

<div id="pending" class="category">
  <div class="cat-head">Pending Applications</div>
  <div class="cat-frame">
    <% if @pending.length == 0 %>
      There are no openings pending applications at this time.
    <% else %>
      <table class="full-list">
        <thead>
          <tr>
            <th>Manager</th>
            <th>Position Type</th>
            <th>Level</th>
            <th>Action</th>
          </tr>
        </thead>
        <tbody>
          <% @pending.each do |opening| %>
            <tr>
              <td><%= opening.lastname %>, <%= opening.firstname %></td>
              <td><%= opening.position %></td>
              <td><%= opening.level.join(";") %></td>
              <td>
                <%= button_to "View", opening_path(opening), :method => "get", class: "action", id: "view" %>
                <%= button_to "Cancel", cancel_opening_path(opening), method: :patch, data: { confirm: 'Are you sure you want to cancel?' }, class: "action", id: "delete" %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
  </div>
</div>

<div id="offered" class="category">
  <div class="cat-head">Job Offered</div>
  <div class="cat-frame">
    <% if @offered.length == 0 %>
      There are no openings with a job offer.
    <% else %>
      <table class="full-list">
        <thead>
          <tr>
            <th>Manager</th>
            <th>Position Type</th>
            <th>Level</th>
            <th>Action</th>
          </tr>
        </thead>
        <tbody>
          <% @offered.each do |opening| %>
            <tr>
              <td><%= opening.lastname %>, <%= opening.firstname %></td>
              <td><%= opening.position %></td>
              <td><%= opening.level.join(";") %></td>
              <td>
                <%= button_to "View", opening_path(opening), :method => "get", class: "action", id: "view" %>
                <%= button_to "Edit", edit_opening_path(opening), :method => "get", class: "action", id: "edit" %>
                <%= button_to "Delete", opening_path(opening), method: :delete, data: { confirm: 'Are you sure you want to delete?' }, class: "action", id: "delete" %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
  </div>
</div>

<div id="accepted" class="category">
  <div class="cat-head">Job Accepted</div>
  <div class="cat-frame">
    <% if @accepted.length == 0 %>
      There are no accepted positions pending onboarding.
    <% else %>
      <table class="full-list">
        <thead>
          <tr>
            <th>Manager</th>
            <th>Position Type</th>
            <th>Level</th>
            <th>Action</th>
          </tr>
        </thead>
        <tbody>
          <% @accepted.each do |opening| %>
            <tr>
              <td><%= opening.lastname %>, <%= opening.firstname %></td>
              <td><%= opening.position %></td>
              <td><%= opening.level.join(";") %></td>
              <td>
                <%= button_to "View", opening_path(opening), :method => "get", class: "action", id: "view" %>
                <%= button_to "Edit", edit_opening_path(opening), :method => "get", class: "action", id: "edit" %>
                <%= button_to "Delete", opening_path(opening), method: :delete, data: { confirm: 'Are you sure you want to delete?' }, class: "action", id: "delete" %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
  </div>
</div>

<div id="completed" class="category">
  <div class="cat-head">Completed Job Requisitions</div>
  <div class="cat-frame">
    <% if @complete.length == 0 %>
      There are no completed job requisitions.
    <% else %>
      <table class="full-list">
        <thead>
          <tr>
            <th>Manager</th>
            <th>Position Type</th>
            <th>Level</th>
            <th>Action</th>
          </tr>
        </thead>
        <tbody>
          <% @complete.each do |opening| %>
            <tr>
              <td><%= opening.lastname %>, <%= opening.firstname %></td>
              <td><%= opening.position %></td>
              <td><%= opening.level.join(";") %></td>
              <td>
                <%= button_to "View", opening_path(opening), :method => "get", class: "action", id: "view" %>
                <%= button_to "Edit", edit_opening_path(opening), :method => "get", class: "action", id: "edit" %>
                <%= button_to "Delete", opening_path(opening), method: :delete, data: { confirm: 'Are you sure you want to delete?' }, class: "action", id: "delete" %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
  </div>
</div>

<div id="cancelled" class="category">
  <div class="cat-head">Cancelled Jobs</div>
  <div class="cat-frame">
    <% if @cancelled.length == 0 %>
      There are no cancelled jobs.
    <% else %>
      <table class="full-list">
        <thead>
          <tr>
            <th>Manager</th>
            <th>Position Type</th>
            <th>Level</th>
            <th>Action</th>
          </tr>
        </thead>
        <tbody>
          <% @cancelled.each do |opening| %>
            <tr>
              <td><%= opening.lastname %>, <%= opening.firstname %></td>
              <td><%= opening.position %></td>
              <td><%= opening.level.join(";") %></td>
              <td>
                <%= button_to "View", opening_path(opening), :method => "get", class: "action", id: "view" %>
                <%= button_to "Reopen", reopen_opening_path(opening), method: :patch, class: "action", id: "delete", :onclick => 'alert("This entry has been updated to Drafts. Please make any necessary updates and submit.")' %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
  </div>
</div>

<div id="offered" class="category">
  <div class="cat-head">Drafts</div>
  <div class="cat-frame">
    <% if @draft.length == 0 %>
      There are drafts for job openings.
    <% else %>
      <table class="full-list">
        <thead>
          <tr>
            <th>Manager</th>
            <th>Position Type</th>
            <th>Level</th>
            <th>Action</th>
          </tr>
        </thead>
        <tbody>
          <% @draft.each do |opening| %>
            <tr>
              <td><%= opening.lastname %>, <%= opening.firstname %></td>
              <td><%= opening.position %></td>
              <td><%= opening.level.join(";") %></td>
              <td>
                <%= button_to "View", opening_path(opening), :method => "get", class: "action", id: "view" %>
                <%= button_to "Edit", edit_opening_path(opening), :method => "get", class: "action", id: "edit" %>
                <%= button_to "Delete", opening_path(opening), method: :delete, data: { confirm: 'Are you sure you want to delete?' }, class: "action", id: "delete" %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
  </div>
</div>

app/views/openings/new.html.erb
<h1>New Opening</h1>

<%= form_with model: @opening do |x| %>
    <div class="section">
        <table>
            <tbody>
                <tr>
                    <td>Manager First Name</td>
                    <td><%= x.text_field :firstname %></td>
                    <td>Manager Last Name</td>
                    <td><%= x.text_field :lastname %></td>
                </tr>
                <tr>
                    <td>Manager Employee ID</td>
                    <td><%= x.text_field :geid %></td>
                    <td rowspan=3>Level</td>
                    <td rowspan=3>
                        <%= x.select(:level, @level, { include_hidden: false },
                            { :multiple => true, :size => @level.length }
                        ) %>
                    </td>
                </tr>
                <tr>
                    <td>Program Position</td>
                    <td><%= x.check_box :program, :checked => true %> Check this box if this position will be a program position.</td>
                </tr>
                <tr>
                    <td>Position Type</td>
                    <td><%= x.select :position, @jobtype, {include_blank: "", selected: ""} %></td>
                </tr>
                <tr>
                    <td>Job Description</td>
                    <td colspan=3><%= x.text_area :description, :rows => 5 %></td>
                </tr>
                <tr>
                    <td>Responsibilities</td>
                    <td colspan=3><%= x.text_area :responsibility, :rows => 5 %></td>
                </tr>
                <tr>
                    <td>Qualifications</td>
                    <td colspan=3><%= x.text_area :qualification, :rows => 5 %></td>
                </tr>
            </tbody>
        </table>
    </div>

    <%= button_tag "Cancel", :type => "submit", name: "cancel", class: "action" %>
    <%= x.submit "Submit", class: "action program", data: { confirm: "You will not be able to edit this entry upon submission. Are you sure you want to submit?"} %>
    <%= x.submit "Save as Draft", class: "action draft" %>
<% end %>

app/views/openings/show.html.erb
<% if @opening.status == "Draft" %>
    <%= link_to 'Edit Entry', edit_opening_path(@opening) %> | 
<% elsif @opening.status == "Pending Applications" %>
    <%= link_to 'Cancel Job Opening', cancel_opening_path(@opening), method: :patch, data: { confirm: 'Are you sure you want to cancel?' } %> | 
<% end %><%= link_to 'Return to Job Openings', openings_path %>
<h1><%= @opening.program ? "Program" : "General" %> <%= @opening.position %> position reporting to <%= @opening.firstname %> <%= @opening.lastname %> (<%= @opening.geid %>)</h1>
<h2>Current status: <%= @opening.status %></h2>

<div class="section">
    <table>
        <tbody>
            <tr>
                <td>Level</td>
                <td><%= @opening.level.join(";") %></td>
            </tr>
            <tr>
                <td>Job Description</td>
                <td><%= @opening.description %></td>
            </tr>
            <tr>
                <td>Responsibilities</td>
                <td><%= @opening.responsibility %></td>
            </tr>
            <tr>
                <td>Qualifications</td>
                <td><%= @opening.qualification %></td>
            </tr>
        </tbody>
    </table>
</div>