config/routes.rb
Rails.application.routes.draw do
  resources :tracks
  resources :exams
  resources :applications
  resources :openings
  resources :designations
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # General Pages
  root 'pages#index'
  get '/guide' => 'pages#guide'

  # Employee List
  resources :participants
  get '/participants/program' => 'participants#indexProg'
  
  # Designation List
  resources :designations

  # Openings List
  resources :openings
  patch '/openings/:id/cancel' => 'openings#cancel', as: :cancel_opening
  patch '/openings/:id/reopen' => 'openings#reopen', as: :reopen_opening

  # Applications List
  get '/open_roles' => 'opening#open'
end

app/models/participant.rb
class Participant < ApplicationRecord
    belongs_to :designation
end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController
  before_action :set_participant, only: %i[ show edit update destroy ]
  before_action :set_fields, only: %i[ new edit ]
  before_action :check_action, only: %i[ create update ]

  # GET /participants or /participants.json
  def index
    @participants = Participant.all.sort_by {|obj| obj.firstname}.sort_by {|obj| obj.lastname}
  end

  def indexProg

  end

  # GET /participants/1 or /participants/1.json
  def show
    
  end

  # GET /participants/new
  def new
    @participant = Participant.new
  end

  # GET /participants/1/edit
  def edit

  end

  # POST /participants or /participants.json
  def create
    @participant = Participant.new(participant_params)

    if @participant.save
      redirect_to participants_path
    else
      puts "Failure"
      puts @participant.errors.full_messages
      render 'new'  
    end
  end

  # PATCH/PUT /participants/1 or /participants/1.json
  def update
    puts "Check"
    @participant = Participant.find(params[@participant.id])
    puts @participant
    if @participant.update(participant_params)
        puts "Success"
        redirect_to participants_path
    else
        puts "Failure"
        render 'edit'
    end
  end

  # DELETE /participants/1 or /participants/1.json
  def destroy
    @participant.destroy
    respond_to do |format|
      format.html { redirect_to participants_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_participant
      @participant = Participant.find_by geid: params[:id]
    end

    # Only allow a list of trusted parameters through.
    def participant_params
      params.require(:participant).permit!
    end

    # Set fields
    def set_fields
      @designations = Designation.all.sort_by {|obj| obj.code}
      @status = ["Active", "Inactive"]
      @replacement = ["N/A", "Pending", "No Replacement Needed", "Replaced"]
    end

    # Check for cancellation
    def check_action
      if params[:cancel]
        redirect_to participants_path
      end
    end
end

app/helpers/participants_helper.rb
module ParticipantsHelper
end

app/views/participants/_form.html.erb
<%= form_with(model: participant) do |form| %>
  <% if participant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(participant.errors.count, "error") %> prohibited this participant from being saved:</h2>

      <ul>
        <% participant.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/participants/edit.html.erb
<%= javascript_pack_tag "participants" %>
<%= stylesheet_link_tag "participants" %>

<div id="employee">
    <h1>Edit Employee</h1>
</div>

<div id="detail">
    <div class="sec-nav select" id="emp-nav">Employee Details</div>
    <div class="sec-nav" id="work-nav">Work Details</div>
    <div class="sec-nav" id="man-nav">Management Details</div>
    <div class="sec-nav" id="stud-nav">Student Details</div>
    <div class="sec-nav" id="conf-nav">Confidential Details</div>

    <%= form_with model: @participant do |x| %>
        <div class="section" id="emp-cont">
            <table>
                <tbody>
                    <tr>
                        <td>First Name</td>
                        <td><%= x.text_field :firstname %></td>
                        <td>Last Name</td>
                        <td><%= x.text_field :lastname %></td>
                    </tr>
                    <tr>
                        <td>Email Address</td>
                        <td><%= x.text_field :email %></td>
                        <td>Employee ID</td>
                        <td><%= x.text_field :geid, class: "integer" %></td>
                    </tr>
                    <tr>
                        <td>Actuarial Designation</td>
                        <td><%= collection_select(:participant, :designation_id, Designation.all, :id, :designation) %></td> 
                        <td></td>
                        <td></td>
                    </tr>
                    <tr>
                        <td>Designation 1</td>
                        <td><%= x.text_field :des1 %></td>
                        <td>Year 1</td>
                        <td><%= x.text_field :year1, class: "integer year" %></td>
                    </tr>
                    <tr>
                        <td>Designation 2</td>
                        <td><%= x.text_field :des2 %></td>
                        <td>Year 2</td>
                        <td><%= x.text_field :year2, class: "integer year" %></td>
                    </tr>
                    <tr>
                        <td>Designation 3</td>
                        <td><%= x.text_field :des3 %></td>
                        <td>Year 3</td>
                        <td><%= x.text_field :year3, class: "integer year" %></td>
                    </tr>
                    <tr>
                        <td>Designation 4</td>
                        <td><%= x.text_field :des4 %></td>
                        <td>Year 4</td>
                        <td><%= x.text_field :year4, class: "integer year" %></td>
                    </tr>
                    <tr>
                        <td>Global Comments</td>
                        <td colspan=3><%= x.text_area :globcom %></td>
                    </tr>
                    <tr>
                        <td>Confidential Comments</td>
                        <td colspan=3><%= x.text_area :confcom %></td>
                    </tr>
                </tbody>
            </table>
        </div>

        <div class="section" id="work-cont">
            <table>
                <tbody>
                    <tr>
                        <td>Line of Business</td>
                        <td><%= x.text_field :lob %></td>
                        <td>Job Title</td>
                        <td><%= x.text_field :title %></td>
                    </tr>
                    <tr>
                        <td>Sub Line of Business</td>
                        <td><%= x.text_field :sublob %></td>
                        <td>Office Location</td>
                        <td><%= x.text_field :location %></td>
                    </tr>
                    <tr>
                        <td>Department</td>
                        <td><%= x.text_field :dep %></td>
                        <td>Employment Status</td>
                        <td><%= x.select :employee, @status %></td>
                    </tr>
                    <tr>
                        <td>Division</td>
                        <td><%= x.text_field :div %></td>
                        <td>Hire Date(s)</td>
                        <td><%= x.date_field :hire %></td>
                    </tr>
                    <tr>
                        <td>Sub Division</td>
                        <td><%= x.text_field :subdiv %></td>
                        <td>Termination Date</td>
                        <td><%= x.date_field :term %></td>
                    </tr>
                    <tr>
                        <td>Section</td>
                        <td><%= x.text_field :sec %></td>
                    </tr>
                </tbody>
            </table>
        </div>

        <div class="section" id="man-cont">
            <table>
                <tbody>
                    <tr>
                        <td>Manager First Name</td>
                        <td><%= x.text_field :manfn %></td>
                        <td>Officer First Name</td>
                        <td><%= x.text_field :offfn %>
                    </tr>
                    <tr>
                        <td>Manager Last Name</td>
                        <td><%= x.text_field :manln %></td>
                        <td>Officer Last Name</td>
                        <td><%= x.text_field :offln %></td>
                    </tr>
                    <tr>
                        <td>Manager Email</td>
                        <td><%= x.text_field :manemail %></td>
                        <td>Officer Email</td>
                        <td><%= x.text_field :offemail %></td>
                    </tr>
                </tbody>
            </table>
        </div>

        <div class="section" id="stud-cont">
            <table>
                <tbody>
                    <tr>
                        <td>Participant Status</td>
                        <td><%= x.select :participant, @status %></td>
                        <td>Exam Standard</td>
                        <td><%= x.date_field :examstd %></td>
                    </tr>
                    <tr>
                        <td>Program Appointment Date</td>
                        <td><%= x.date_field :program %></td>
                        <td>FSA Track</td>
                        <td><%= x.text_field :fsa %></td>
                    </tr>
                    <tr>
                        <td>Replacement Status</td>
                        <td><%= x.select :replace, @replacement %></td>
                        <td>Pass Rate</td>
                        <td>This field will be automatically calculated</td>
                    </tr>
                </tbody>
            </table>
        </div>

        <div class="section" id="conf-cont">
            <table>
                <tbody>
                    <tr>
                        <td>Year of Data</td>
                        <td colspan=3><%= x.text_field :datayr, class: "integer year" %></td>
                    </tr>
                    <tr>
                        <td><span class="cyr"></span> Salary</td>
                        <td><%= x.text_field :salaryc %></td>
                        <td><span class="cyr"></span> Rating</td>
                        <td><%= x.text_field :rating %></td>
                    </tr>
                    <tr>
                        <td><span class="cyr1"></span> Salary</td>
                        <td><%= x.text_field :salaryc1 %></td>
                        <td><span class="cyr1"></span> Rating</td>
                        <td><%= x.text_field :rating1 %></td>
                    </tr>
                    <tr>
                        <td><span class="cyr2"></span> Salary</td>
                        <td><%= x.text_field :salaryc2 %></td>
                        <td><span class="cyr2"></span> Rating</td>
                        <td><%= x.text_field :rating2 %></td>
                    </tr>
                    <tr>
                        <td><span class="cyr3"></span> Salary</td>
                        <td><%= x.text_field :salaryc3 %></td>
                        <td><span class="cyr3"></span> Rating</td>
                        <td><%= x.text_field :rating3 %></td>
                    </tr>
                    <tr>
                        <td><span class="cyr"></span> Bonus</td>
                        <td><%= x.text_field :bonus %></td>
                    </tr>
                    <tr>
                        <td><span class="cyr1"></span> Bonus</td>
                        <td><%= x.text_field :bonus1 %></td>
                    </tr>
                    <tr>
                        <td><span class="cyr2"></span> Bonus</td>
                        <td><%= x.text_field :bonus2 %></td>
                    </tr>
                    <tr>
                        <td><span class="cyr3"></span> Bonus</td>
                        <td><%= x.text_field :bonus3 %></td>
                    </tr>
                </tbody>
            </table>
        </div>

        <%= button_tag "Cancel", :type => "submit", name: "cancel", class: "action" %>
        <%= x.submit "Save", class: "action program" %> 
    <% end %>
</div>

app/views/participants/index.html.erb
<%= stylesheet_link_tag "participants" %>
<h1>Employee List</h1>

<%= button_to 'New Employee', new_participant_path, :method => "get", class: "action", id: "new" %>
<table class="full-list">
  <thead>
    <tr>
      <th>Full Name</th>
      <th>Actuarial Designation</th>
      <th>Job Title</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    <% @participants.each do |participant| %>
      <tr>
        <td>
          <%= participant.lastname + ', ' + participant.firstname %>
        </td>
        <td><%= participant.designation.designation %></td>
        <td><%= participant.title %></td>
        <td>
          <%= button_to "View", participant_path(participant.geid), :method => "get", class: "action", id: "view" %>
          <%= button_to "Edit", edit_participant_path(participant.geid), :method => "get", class: "action", id: "edit" %>
          <%= button_to "Delete", participant_path(participant.geid), method: :delete, data: { confirm: 'Are you sure you want to delete ' + participant.firstname + ' ' + participant.lastname + '?' }, class: "action", id: "delete" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/participants/new.html.erb
<%= javascript_pack_tag "participants" %>
<%= stylesheet_link_tag "participants" %>

<div id="employee">
    <h1>New Employee</h1>
</div>

<div id="detail">
    <div class="sec-nav select" id="emp-nav">Employee Details</div>
    <div class="sec-nav" id="work-nav">Work Details</div>
    <div class="sec-nav" id="man-nav">Management Details</div>
    <div class="sec-nav" id="stud-nav">Student Details</div>
    <div class="sec-nav" id="conf-nav">Confidential Details</div>

    <%= form_with model: @participant do |x| %>
        <div class="section" id="emp-cont">
            <table>
                <tbody>
                    <tr>
                        <td>First Name</td>
                        <td><%= x.text_field :firstname %></td>
                        <td>Last Name</td>
                        <td><%= x.text_field :lastname %></td>
                    </tr>
                    <tr>
                        <td>Email Address</td>
                        <td><%= x.text_field :email %></td>
                        <td>Employee ID</td>
                        <td><%= x.text_field :geid, class: "integer" %></td>
                    </tr>
                    <tr>
                        <td>Actuarial Designation</td>
                        <td><%= collection_select(:participant, :designation_id, Designation.all, :id, :designation, {include_blank: "", selected: ""}) %></td> 
                        <td></td>
                        <td></td>
                    </tr>
                    <tr>
                        <td>Designation 1</td>
                        <td><%= x.text_field :des1 %></td>
                        <td>Year 1</td>
                        <td><%= x.text_field :year1, class: "integer year" %></td>
                    </tr>
                    <tr>
                        <td>Designation 2</td>
                        <td><%= x.text_field :des2 %></td>
                        <td>Year 2</td>
                        <td><%= x.text_field :year2, class: "integer year" %></td>
                    </tr>
                    <tr>
                        <td>Designation 3</td>
                        <td><%= x.text_field :des3 %></td>
                        <td>Year 3</td>
                        <td><%= x.text_field :year3, class: "integer year" %></td>
                    </tr>
                    <tr>
                        <td>Designation 4</td>
                        <td><%= x.text_field :des4 %></td>
                        <td>Year 4</td>
                        <td><%= x.text_field :year4, class: "integer year" %></td>
                    </tr>
                    <tr>
                        <td>Global Comments</td>
                        <td colspan=3><%= x.text_area :globcom %></td>
                    </tr>
                    <tr>
                        <td>Confidential Comments</td>
                        <td colspan=3><%= x.text_area :confcom %></td>
                    </tr>
                </tbody>
            </table>
        </div>

        <div class="section" id="work-cont">
            <table>
                <tbody>
                    <tr>
                        <td>Line of Business</td>
                        <td><%= x.text_field :lob %></td>
                        <td>Job Title</td>
                        <td><%= x.text_field :title %></td>
                    </tr>
                    <tr>
                        <td>Sub Line of Business</td>
                        <td><%= x.text_field :sublob %></td>
                        <td>Office Location</td>
                        <td><%= x.text_field :location %></td>
                    </tr>
                    <tr>
                        <td>Department</td>
                        <td><%= x.text_field :dep %></td>
                        <td>Employment Status</td>
                        <td><%= x.select :employee, @status, :selected => "Active" %></td>
                    </tr>
                    <tr>
                        <td>Division</td>
                        <td><%= x.text_field :div %></td>
                        <td>Hire Date(s)</td>
                        <td><%= x.date_field :hire %></td>
                    </tr>
                    <tr>
                        <td>Sub Division</td>
                        <td><%= x.text_field :subdiv %></td>
                        <td>Termination Date</td>
                        <td><%= x.date_field :term %></td>
                    </tr>
                    <tr>
                        <td>Section</td>
                        <td><%= x.text_field :sec %></td>
                    </tr>
                </tbody>
            </table>
        </div>

        <div class="section" id="man-cont">
            <table>
                <tbody>
                    <tr>
                        <td>Manager First Name</td>
                        <td><%= x.text_field :manfn %></td>
                        <td>Officer First Name</td>
                        <td><%= x.text_field :offfn %>
                    </tr>
                    <tr>
                        <td>Manager Last Name</td>
                        <td><%= x.text_field :manln %></td>
                        <td>Officer Last Name</td>
                        <td><%= x.text_field :offln %></td>
                    </tr>
                    <tr>
                        <td>Manager Email</td>
                        <td><%= x.text_field :manemail %></td>
                        <td>Officer Email</td>
                        <td><%= x.text_field :offemail %></td>
                    </tr>
                </tbody>
            </table>
        </div>

        <div class="section" id="stud-cont">
            <table>
                <tbody>
                    <tr>
                        <td>Participant Status</td>
                        <td><%= x.select :participant, @status, :selected => "Active" %></td>
                        <td>Exam Standard</td>
                        <td><%= x.date_field :examstd %></td>
                    </tr>
                    <tr>
                        <td>Program Appointment Date</td>
                        <td><%= x.date_field :program %></td>
                        <td>FSA Track</td>
                        <td><%= x.text_field :fsa %></td>
                    </tr>
                    <tr>
                        <td>Replacement Status</td>
                        <td><%= x.select :replace, @replacement, :selected => "N/A" %></td>
                        <td>Pass Rate</td>
                        <td>This field will be automatically calculated</td>
                    </tr>
                </tbody>
            </table>
        </div>

        <div class="section" id="conf-cont">
            <table>
                <tbody>
                    <tr>
                        <td>Year of Data</td>
                        <td colspan=3><%= x.text_field :datayr, class: "integer year" %></td>
                    </tr>
                    <tr>
                        <td><span class="cyr"></span> Salary</td>
                        <td><%= x.text_field :salaryc %></td>
                        <td><span class="cyr"></span> Rating</td>
                        <td><%= x.text_field :rating %></td>
                    </tr>
                    <tr>
                        <td><span class="cyr1"></span> Salary</td>
                        <td><%= x.text_field :salaryc1 %></td>
                        <td><span class="cyr1"></span> Rating</td>
                        <td><%= x.text_field :rating1 %></td>
                    </tr>
                    <tr>
                        <td><span class="cyr2"></span> Salary</td>
                        <td><%= x.text_field :salaryc2 %></td>
                        <td><span class="cyr2"></span> Rating</td>
                        <td><%= x.text_field :rating2 %></td>
                    </tr>
                    <tr>
                        <td><span class="cyr3"></span> Salary</td>
                        <td><%= x.text_field :salaryc3 %></td>
                        <td><span class="cyr3"></span> Rating</td>
                        <td><%= x.text_field :rating3 %></td>
                    </tr>
                    <tr>
                        <td><span class="cyr"></span> Bonus</td>
                        <td><%= x.text_field :bonus %></td>
                    </tr>
                    <tr>
                        <td><span class="cyr1"></span> Bonus</td>
                        <td><%= x.text_field :bonus1 %></td>
                    </tr>
                    <tr>
                        <td><span class="cyr2"></span> Bonus</td>
                        <td><%= x.text_field :bonus2 %></td>
                    </tr>
                    <tr>
                        <td><span class="cyr3"></span> Bonus</td>
                        <td><%= x.text_field :bonus3 %></td>
                    </tr>
                </tbody>
            </table>
        </div>
        
        <%= button_tag "Cancel", :type => "submit", name: "cancel", class: "action" %>
        <%= x.submit "Save", class: "action program" %> 
    <% end %>
</div>

app/views/participants/show.html.erb
<%= javascript_pack_tag "participants" %>
<%= stylesheet_link_tag "participants" %>

<div id="employee">
    <%= link_to 'Edit Entry', edit_participant_path(@participant.geid) %> | <%= link_to 'Return to Employee List', participants_path %>
    <h1><%= @participant.lastname %>, <%= @participant.firstname %></h1>
    <h2><%= @participant.geid %></h2>
</div>

<div id="prog-det">
    <%= button_to "Attachments", "/", class: "action program" %>
    <%= button_to "Exam History", "/", class: "action program" %>
    <%= button_to "Reimbursements", "/", class: "action program" %>
    <%= button_to "Salary Actions", "/", class: "action program" %>
    <%= button_to "Work History", "/", class: "action program" %>
</div>

<div id="detail">
    <div class="sec-nav select" id="emp-nav">Employee Details</div>
    <div class="sec-nav" id="work-nav">Work Details</div>
    <div class="sec-nav" id="man-nav">Management Details</div>
    <div class="sec-nav" id="stud-nav">Student Details</div>
    <div class="sec-nav" id="conf-nav">Confidential Details</div>

    <div class="section" id="emp-cont">
        <table>
            <tbody>
                <tr>
                    <td>Email Address</td>
                    <td colspan=3><%= @participant.email %></td>
                </tr>
                <tr>
                    <td>Actuarial Designation</td>
                    <td colspan=3><%= @participant.designation.designation %></td>
                </tr>
                <tr>
                    <td>Designation 1</td>
                    <td><%= @participant.des1 %></td>
                    <td>Year 1</td>
                    <td><%= @participant.year1 %></td>
                </tr>
                <tr>
                    <td>Designation 2</td>
                    <td><%= @participant.des2 %></td>
                    <td>Year 2</td>
                    <td><%= @participant.year2 %></td>
                </tr>
                <tr>
                    <td>Designation 3</td>
                    <td><%= @participant.des3 %></td>
                    <td>Year 3</td>
                    <td><%= @participant.year3 %></td>
                </tr>
                <tr>
                    <td>Designation 4</td>
                    <td><%= @participant.des4 %></td>
                    <td>Year 4</td>
                    <td><%= @participant.year4 %></td>
                </tr>
                <tr>
                    <td>Global Comments</td>
                    <td colspan=3><%= @participant.globcom %></td>
                </tr>
                <tr>
                    <td>Confidential Comments</td>
                    <td colspan=3><%= @participant.confcom %></td>
                </tr>
            </tbody>
        </table>
    </div>

    <div class="section" id="work-cont">
        <table>
            <tbody>
                <tr>
                    <td>Line of Business</td>
                    <td><%= @participant.lob %></td>
                    <td>Job Title</td>
                    <td></td>
                </tr>
                <tr>
                    <td>Sub Line of Business</td>
                    <td><%= @participant.sublob %></td>
                    <td>Office Location</td>
                    <td><%= @participant.location %></td>
                </tr>
                <tr>
                    <td>Department</td>
                    <td><%= @participant.dep %></td>
                    <td>Employment Status</td>
                    <td><%= @participant.employee %></td>
                </tr>
                <tr>
                    <td>Division</td>
                    <td><%= @participant.div %></td>
                    <td>Hire Date(s)</td>
                    <td><%= @participant.hire %></td>
                </tr>
                <tr>
                    <td>Sub Division</td>
                    <td><%= @participant.subdiv %></td>
                    <td>Termination Date</td>
                    <td><%= @participant.term %></td>
                </tr>
                <tr>
                    <td>Section</td>
                    <td><%= @participant.sec %></td>
                    
                </tr>
            </tbody>
        </table>
    </div>

    <div class="section" id="man-cont">
        <table>
            <tbody>
                <tr>
                    <td>Manager First Name</td>
                    <td><%= @participant.manfn %></td>
                    <td>Officer First Name</td>
                    <td><%= @participant.offfn %>
                </tr>
                <tr>
                    <td>Manager Last Name</td>
                    <td><%= @participant.manln %></td>
                    <td>Officer Last Name</td>
                    <td><%= @participant.offln %></td>
                </tr>
                <tr>
                    <td>Manager Email</td>
                    <td><%= @participant.manemail %></td>
                    <td>Officer Email</td>
                    <td><%= @participant.offemail %></td>
                </tr>
            </tbody>
        </table>
    </div>

    <div class="section" id="stud-cont">
        <table>
            <tbody>
                <tr>
                    <td>Participant Status</td>
                    <td><%= @participant.participant %></td>
                    <td>Exam Standard</td>
                    <td><%= @participant.examstd %></td>
                </tr>
                <tr>
                    <td>Program Appointment Date</td>
                    <td><%= @participant.program %></td>
                    <td>FSA Track</td>
                    <td><%= @participant.fsa %></td>
                </tr>
                <tr>
                    <td>Replacement Status</td>
                    <td><%= @participant.replace %></td>
                    <td>Pass Rate</td>
                    <td></td>
                </tr>
            </tbody>
        </table>
    </div>

    <div class="section" id="conf-cont">
        <table>
            <tbody>
                <tr>
                    <td><span class="cyr"></span> Salary</td>
                    <td><%= @participant.salaryc %></td>
                    <td><span class="cyr"></span> Rating</td>
                    <td><%= @participant.rating %></td>
                </tr>
                <tr>
                    <td><span class="cyr1"></span> Salary</td>
                    <td><%= @participant.salaryc1 %></td>
                    <td><span class="cyr1"></span> Rating</td>
                    <td><%= @participant.rating1 %></td>
                </tr>
                <tr>
                    <td><span class="cyr2"></span> Salary</td>
                    <td><%= @participant.salaryc2 %></td>
                    <td><span class="cyr2"></span> Rating</td>
                    <td><%= @participant.rating2 %></td>
                </tr>
                <tr>
                    <td><span class="cyr3"></span> Salary</td>
                    <td><%= @participant.salaryc3 %></td>
                    <td><span class="cyr3"></span> Rating</td>
                    <td><%= @participant.rating3 %></td>
                </tr>
                <tr>
                    <td><span class="cyr"></span> Bonus</td>
                    <td colspan=3><%= @participant.bonus %></td>
                </tr>
                <tr>
                    <td><span class="cyr1"></span> Bonus</td>
                    <td colspan=3><%= @participant.bonus1 %></td>
                </tr>
                <tr>
                    <td><span class="cyr2"></span> Bonus</td>
                    <td colspan=3><%= @participant.bonus2 %></td>
                </tr>
                <tr>
                    <td><span class="cyr3"></span> Bonus</td>
                    <td colspan=3><%= @participant.bonus3 %></td>
                </tr>
            </tbody>
        </table>
    </div>
</div>