config/routes.rb
Rails.application.routes.draw do
  resources :tracks
  resources :exams
  resources :applications
  resources :openings
  resources :designations
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # General Pages
  root 'pages#index'
  get '/guide' => 'pages#guide'

  # Employee List
  resources :participants
  get '/participants/program' => 'participants#indexProg'
  
  # Designation List
  resources :designations

  # Openings List
  resources :openings
  patch '/openings/:id/cancel' => 'openings#cancel', as: :cancel_opening
  patch '/openings/:id/reopen' => 'openings#reopen', as: :reopen_opening

  # Applications List
  get '/open_roles' => 'opening#open'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InterviewEvaluation</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;500;700&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header>
      <nav>
        <ul>
          <li><%= link_to "Home", root_path() %></li>
          <li>Associate Information <div class="nav-static">▶</div><div class="nav-hover">▼</div>
            <ul>
              <li><%= link_to "All Associates", participants_path() %></li>
              <!--<li>Current Participants</li>-->
            </ul>
          </li>
          <li>Recruiting <div class="nav-static">▶</div><div class="nav-hover">▼</div>
            <ul>
              <li>Job Requisitions <div class="nav-static">▶</div><div class="nav-hover">▼</div>
                <ul>
                  <li><%= link_to "All Requisitions", openings_path() %></li>
                  <li><%= link_to "Public Open Positions", open_roles_path() %></li>
                </ul>
              </li>
              <!--<li>Candidates <div class="nav-static">▶</div><div class="nav-hover">▼</div>
                <ul>
                  <li>All Candidates</li>
                  <li>Internship</li>
                  <li>Full Time</li>
                  <li>Pending Interviews</li>
                  <li>Incoming Hires</li>
                </ul>
              </li>
              <li>Interviews <div class="nav-static">▶</div><div class="nav-hover">▼</div>
                <ul>
                  <li>All Interviews</li>
                  <li>Upcoming Interviews</li>
                  <li>Interviews by Interviewer</li>
                </ul>
              </li>
              <li>Evaluations <div class="nav-static">▶</div><div class="nav-hover">▼</div>
                <ul>
                  <li>All Evaluations</li>
                  <li>Evaluations by Candidate</li>
                  <li>Evaluations by Interviewer</li>
                </ul>
              </li>-->
            </ul>
          </li>          
          <li>Site Management <div class="nav-static">▶</div><div class="nav-hover">▼</div>
            <ul>
              <li><%= link_to "Actuarial Designations", designations_path() %></li>
              <li><%= link_to "Track Master", tracks_path() %></li>
              <li><%= link_to "Exam Master", exams_path() %></li> 
            </ul>
          </li>
          <!--<li><%= link_to "User Guide", guide_path() %></li>-->
        </ul>
      </nav>
    </header>
    <div id="content">
      <%= yield %>
    </div>
  </body>
</html>